/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daa;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.util.Random;

/**
 *
 * @author Dasuni Anupama
 */
public class selectionSort extends javax.swing.JFrame implements Runnable{
    int A[];
    int swap_mode;
    Thread th;
   
    JTextField[] array;
    
    /**
     * Creates new form simulator
     */
    public selectionSort() {
        initComponents();
        
        th = new Thread(this); 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        executeSelection = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanelAlgo4 = new javax.swing.JPanel();
        lblLine29 = new javax.swing.JLabel();
        lblLine30 = new javax.swing.JLabel();
        lblLine31 = new javax.swing.JLabel();
        lblLine32 = new javax.swing.JLabel();
        lblLine33 = new javax.swing.JLabel();
        lblLine34 = new javax.swing.JLabel();
        lblLine35 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        executeSelection.setText("Selection Sort ");
        executeSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeSelectionActionPerformed(evt);
            }
        });

        jButton11.setText("Back ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jPanelAlgo4.setBackground(new java.awt.Color(255, 255, 255));

        lblLine29.setBackground(new java.awt.Color(255, 255, 255));
        lblLine29.setText("1.  n ← length[A] ");
        lblLine29.setName("lblLine1"); // NOI18N
        lblLine29.setOpaque(true);

        lblLine30.setBackground(new java.awt.Color(255, 255, 255));
        lblLine30.setText("2.  for j ← 1 to n − 1 ");
        lblLine30.setName("lblLine2"); // NOI18N
        lblLine30.setOpaque(true);

        lblLine31.setBackground(new java.awt.Color(255, 255, 255));
        lblLine31.setText("3.          do smallest ← j ");
        lblLine31.setName("lblLine3"); // NOI18N
        lblLine31.setOpaque(true);

        lblLine32.setBackground(new java.awt.Color(255, 255, 255));
        lblLine32.setText("4.               for i ← j + 1 to n ");
        lblLine32.setName("lblLine4"); // NOI18N
        lblLine32.setOpaque(true);

        lblLine33.setBackground(new java.awt.Color(255, 255, 255));
        lblLine33.setText("5.                    do if A[ i ] < A[smallest] ");
        lblLine33.setName("lblLine5"); // NOI18N
        lblLine33.setOpaque(true);

        lblLine34.setBackground(new java.awt.Color(255, 255, 255));
        lblLine34.setText("6.                               then smallest ← i ");
        lblLine34.setName("lblLine6"); // NOI18N
        lblLine34.setOpaque(true);

        lblLine35.setBackground(new java.awt.Color(255, 255, 255));
        lblLine35.setText("7.           exchange A[ j ] ↔ A[smallest]");
        lblLine35.setName("lblLine7"); // NOI18N
        lblLine35.setOpaque(true);

        javax.swing.GroupLayout jPanelAlgo4Layout = new javax.swing.GroupLayout(jPanelAlgo4);
        jPanelAlgo4.setLayout(jPanelAlgo4Layout);
        jPanelAlgo4Layout.setHorizontalGroup(
            jPanelAlgo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlgo4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlgo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLine31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLine29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLine30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLine32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLine33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLine34, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(lblLine35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelAlgo4Layout.setVerticalGroup(
            jPanelAlgo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlgo4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLine29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLine30, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLine31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLine32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLine33, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLine34, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLine35, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jLabel1.setText("Insert Array ");

        jLabel2.setText("Sorted Array ");

        jButton1.setText("Random");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(executeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(198, 198, 198)
                                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(430, 430, 430))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(443, 443, 443))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(861, 861, 861)
                    .addComponent(jPanelAlgo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jPanelAlgo4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(170, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeSelectionActionPerformed
        // TODO add your handling code here:
        
        A=new int[10];
        
        
        if(jTextField1.getText().isEmpty() || jTextField1.getText().contains("[a-zA-Z]"))
        {
            JOptionPane.showMessageDialog(null, "Please insert a number", "warning", 2);
            jTextField1.grabFocus();
        }
        else if(jTextField2.getText().isEmpty() || jTextField2.getText().contains("[a-zA-Z]"))
        {
            JOptionPane.showMessageDialog(null,"Please insert a number", "warning", 2);
            jTextField2.grabFocus();
        }
        else if(jTextField3.getText().isEmpty() || jTextField3.getText().contains("[a-zA-Z]"))
        {
            JOptionPane.showMessageDialog(null,"Please insert a number", "warning", 2);
            jTextField3.grabFocus();
        }
        else if(jTextField4.getText().isEmpty() || jTextField4.getText().contains("[a-zA-Z]"))
        {
            JOptionPane.showMessageDialog(null, "Please insert a number", "warning", 2);
            jTextField4.grabFocus();
        }
        else if(jTextField5.getText().isEmpty() || jTextField5.getText().contains("[a-zA-Z]"))
        {
            JOptionPane.showMessageDialog(null, "Please insert a number", "warning", 2);
            jTextField5.grabFocus();
        }
        else if(jTextField6.getText().isEmpty() || jTextField6.getText().contains("[a-zA-Z]"))
        {
            JOptionPane.showMessageDialog(null, "Please insert a number", "warning", 2);
            jTextField6.grabFocus();
        }
        else if(jTextField7.getText().isEmpty() || jTextField7.getText().contains("[a-zA-Z]"))
        {
            JOptionPane.showMessageDialog(null, "Please insert a number", "warning", 2);
            jTextField7.grabFocus();
        }
        else if(jTextField8.getText().isEmpty() || jTextField8.getText().contains("[a-zA-Z]"))
        {
            JOptionPane.showMessageDialog(null,"Please insert a number", "warning", 2);
            jTextField8.grabFocus();
        }
        else if(jTextField9.getText().isEmpty() || jTextField9.getText().contains("[a-zA-Z]"))
        {
            JOptionPane.showMessageDialog(null,"Please insert a number", "warning", 2);
            jTextField9.grabFocus();
        }
        else if(jTextField10.getText().isEmpty() || jTextField10.getText().contains("[a-zA-Z]"))
        {
            JOptionPane.showMessageDialog(null,"Please insert a number", "warning", 2);
            jTextField10.grabFocus();
        }
        else
        {
            
             jTextField11.setText(jTextField1.getText());
             jTextField12.setText(jTextField2.getText());
             jTextField13.setText(jTextField3.getText());
             jTextField14.setText(jTextField4.getText());
             jTextField15.setText(jTextField5.getText());
             jTextField16.setText(jTextField6.getText());
             jTextField17.setText(jTextField7.getText());
             jTextField18.setText(jTextField8.getText());
             jTextField19.setText(jTextField9.getText());
             jTextField20.setText(jTextField10.getText());
                    
                  
            A[0]=Integer.parseInt(jTextField1.getText());
            A[1]=Integer.parseInt(jTextField2.getText());
            A[2]=Integer.parseInt(jTextField3.getText());
            A[3]=Integer.parseInt(jTextField4.getText());
            A[4]=Integer.parseInt(jTextField5.getText());
            A[5]=Integer.parseInt(jTextField6.getText());
            A[6]=Integer.parseInt(jTextField7.getText());
            A[7]=Integer.parseInt(jTextField8.getText());
            A[8]=Integer.parseInt(jTextField9.getText());
            A[9]=Integer.parseInt(jTextField10.getText());
             
         
    
           array=new JTextField[]{jTextField11,jTextField12,jTextField13,jTextField14,jTextField15,jTextField16,jTextField17,jTextField18,jTextField19,jTextField20};
            swap_mode =1;
            th.start();
        }
        
    }//GEN-LAST:event_executeSelectionActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
        SortHome h=new SortHome();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Random rs=new Random();
        jTextField1.setText(String.valueOf(rs.nextInt(200)));
        jTextField2.setText(String.valueOf(rs.nextInt(200)));
        jTextField3.setText(String.valueOf(rs.nextInt(200)));
        jTextField4.setText(String.valueOf(rs.nextInt(200)));
        jTextField5.setText(String.valueOf(rs.nextInt(200)));
        jTextField6.setText(String.valueOf(rs.nextInt(200)));
        jTextField7.setText(String.valueOf(rs.nextInt(200)));
        jTextField8.setText(String.valueOf(rs.nextInt(200)));
        jTextField9.setText(String.valueOf(rs.nextInt(200)));
        jTextField10.setText(String.valueOf(rs.nextInt(200)));
                 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectionSort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton executeSelection;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelAlgo4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblLine29;
    private javax.swing.JLabel lblLine30;
    private javax.swing.JLabel lblLine31;
    private javax.swing.JLabel lblLine32;
    private javax.swing.JLabel lblLine33;
    private javax.swing.JLabel lblLine34;
    private javax.swing.JLabel lblLine35;
    // End of variables declaration//GEN-END:variables

    
    
    
    public void run() {
         int temp,smallest;
         
        if (swap_mode == 1) 
        {
             for(int j=0; j<A.length-1; j++)
            {
                smallest=j;
            
                for(int i=j+1; i<A.length; i++)
                {
                    if(A[i]<A[smallest] )
                    {    
                        smallest=i;
                    }
                }
            
                temp=A[smallest];
                A[smallest]=A[j];
                A[j]=temp;
                try
                    {
                        swappping(j,smallest);
                    }
                    catch(InterruptedException ex){}
        }
    }

}
 public void swappping(int n1, int n2) throws InterruptedException {

        
        
        for (int i = 0; i < 25; i++) {

            array[n1].setLocation(array[n1].getLocation().x, array[n1].getLocation().y + 1);
            array[n2].setLocation(array[n2].getLocation().x, array[n2].getLocation().y - 1);
            th.sleep(25);
        }

        int length = array[n2].getLocation().x - array[n1].getLocation().x;
        for (int i = 0; i < length; i++) {
            array[n1].setLocation(array[n1].getLocation().x + 1, array[n1].getLocation().y);
            array[n2].setLocation(array[n2].getLocation().x - 1, array[n2].getLocation().y);
            th.sleep(25);
        }

        for (int i = 0; i < 25; i++) {
            array[n1].setLocation(array[n1].getLocation().x, array[n1].getLocation().y - 1);
            array[n2].setLocation(array[n2].getLocation().x, array[n2].getLocation().y + 1);
            th.sleep(25);
        }
        
        JTextField temp = array[n1];
        array[n1] = array[n2];
        array[n2] = temp;

        
    }

}



